version: "2"
services:
  app:
    build: .
    image: keboola/wr-dropbox-v2
    stdin_open: true
    tty: true
  dev:
    image: keboola/wr-dropbox-v2
    volumes:
      - ./src:/code/src
      - ./vendor:/code/vendor
    tty: true
    stdin_open: true
